const RATES={uk:{rate:51,sym:"грн",pre:false,round:50},pl:{rate:4.26,sym:"zł",pre:false,round:10},en:{rate:1,sym:"€",pre:true,round:1}};
function priceFor(eur,lang){const r=RATES[lang];let v=eur*r.rate;v=Math.round(v/r.round)*r.round;const num=v.toLocaleString(lang==='uk'?'uk-UA':lang==='pl'?'pl-PL':'en-IE');return r.pre?`${r.sym}${num}`:`${num} ${r.sym}`;}

const DATA={
 uk:{
  eyebrow:"Тренер · Фітнес-модель · Вроцлав 🇵🇱",
  h1:'Твоє <i>тіло мрії</i> —<br>побудуємо <b>разом</b>',
  herosub:"Я Олена — тренер із Вроцлава. 20 років у спорті, виступаю на міжнародній сцені. Допоможу тобі привести тіло у форму без крайнощів.",
  cta1:"Обрати програму",cta2:"Про мене",badge:"на сцені з",
  nav:{about:"Про мене",ach:"Досягнення",process:"Як працюю",whom:"Для кого",values:"Цінності",services:"Послуги",creds:"Освіта",faq:"Питання",navcta:"Обрати програму"},
  offerLabel:"Знижка <b>−20%</b> на всі програми до кінця тижня",
  tD:"днів",tH:"год",tM:"хв",tS:"сек",
  spotsLabel:"Залишилось місць:",saveBadge:"−20%",
  fabText:"Написати",incEye:"📦 Що входить",incTitle:"Що ти <b>отримаєш</b>",includes:[{t:"Дієта",feat:false,items:["Індивідуальний план харчування","Розрахунок калорій і БЖВ","Список продуктів і заміни","Рекомендації під твій графік","Підтримка при запуску плану"]},{t:"Марафон",feat:true,items:["Програма тренувань на весь курс","План харчування","Щоденна підтримка у групі","Щотижневий контроль прогресу","Мотивація та дисципліна","Відповіді на питання від тренера"]},{t:"Програма",feat:false,items:["Персональна програма тренувань","Відео-техніка вправ","Варіанти для дому та залу","Схема прогресії навантажень","Поради щодо відновлення"]}],
  mq:["20+ років досвіду","Абсолютна чемпіонка Польщі","Міжнародна сцена","Дієтолог · нутриціолог","Mini MBA","Індивідуальний підхід"],
  aboutEye:"Про мене",aboutTitle:'Фітнес — це <b>мій шлях</b>',
  aboutP1:"Фітнес зі мною понад 20 років. Я пройшла шлях від дівчини, яка тренувалася для себе, до спортсменки на міжнародній сцені.",
  aboutP2:"Результат — це не магія, а система і регулярність. Саме цього я вчу своїх клієнток.",
  aboutQuote:"«У роботі з клієнтами я поєдную свій 20-річний тренувальний досвід, знання з курсів і особистий досвід підготовки до змагань.»",
  stat1:"років у спорті",stat2:"перший виступ",stat3:"чемпіонські титули Masters",
  achEye:"🏆 Спортивні досягнення",achTitle:'Здобуто <b>на сцені</b>',
  achIntro:"Почала у 2014-му — бронза вже на дебюті. Після перерви повернулася сильнішою і виступаю у категорії Fit Model на турнірах Польщі та Італії.",
  titles:[{i:"🏆",t:"Абсолютна чемпіонка Польщі — Open Fit Model"},{i:"🥇",t:"Дворазова чемпіонка Masters"},{i:"🥈",t:"Срібло EuroMasters (Італія), Masters 35+ та 40+"},{i:"🏅",t:"TOP-5 Flex Weekend Pro Qualifier, Мілан"}],
  timeline:[{y:"2014",ev:[{p:"Чемпіонат України (WBPF)",r:"🥉 Бронза — дебютний старт"}]},{y:"2025",ev:[{p:"NPC Poland",r:"🏆 Overall Open Fit Model · 2×🥇 Masters · 🥈 Open Class B"},{p:"EuroMasters (Італія)",r:"🥈 Masters 35+ · 🥈 Masters 40+"}]},{y:"2026",ev:[{p:"League of Champions Pro Qualifier",r:"2×🥇 Masters · 🥈 Open Class B"},{p:"Natural & Regional Qualifier",r:"Призові місця у Masters та Novice"},{p:"Flex Weekend Pro Qualifier (Мілан)",r:"🏅 TOP-5 Fit Model Open Class B"}]}],
  procEye:"🧭 Як проходить робота",procTitle:'Покроковий <b>супровід</b>',
  steps:[{h:"Знайомимось",p:"Дізнаюся про твій режим, звички, здоров’я і ціль."},{h:"Анкета",p:"Заповнюєш анкету — так я бачу твій рівень і обмеження."},{h:"Ціль",p:"Визначаємо, чого хочеш: схуднути, підтягнути тіло чи форма до події."},{h:"План",p:"Складаю харчування і тренування під твій ритм життя."},{h:"Контроль",p:"Щотижня дивимось фото, заміри, вагу і самопочуття."},{h:"Корекції",p:"Коригую план, щоб результат ішов без стресу для тіла."}],
  resTitle:"Результати за 2–3 місяці",
  results:["зменшення об’ємів","зниження ваги","підтягнуте тіло","краща форма сідниць і ніг","покращення постави","більше енергії","контроль харчування","менше набряків","дисципліна і режим","впевненість у собі"],
  whoEye:"🎯 Для кого",whoTitle:'З ким я <b>працюю</b>',
  goals:["схуднути","підтягнути тіло","покращити форму сідниць, ніг, спини та плечей","навчитися правильно харчуватися","повернути впевненість у собі","підготуватися до фотосесії, відпустки або змагань"],
  valEye:"💜 Мої цінності",valTitle:'Підхід, у який я <b>вірю</b>',
  values:[{t:"Дисципліна",p:"Саме регулярні дії створюють результат."},{t:"Здоров’я",p:"Форма не повинна будуватися ціною виснаження."},{t:"Стабільність",p:"Короткі ривки не дають довготривалого результату."},{t:"Любов до себе",p:"Зміни починаються з турботи про себе, а не з ненависті до тіла."},{t:"Тривалий результат",p:"Моя мета — навчити тебе зберігати форму, а не лише її досягти."}],
  servEye:"✨ Послуги",servTitle:'Обери свій <b>формат</b>',
  services:[{tag:"Харчування",title:"Дієта",desc:"Індивідуальний план харчування під твої цілі, тип тіла та спосіб життя.",eur:49,disc:.2,spots:6,total:10,per:"/ план"},{tag:"Найпопулярніше",title:"Марафон",desc:"Груповий курс трансформації: тренування, харчування та підтримка щодня.",eur:99,disc:.2,spots:3,total:12,per:"/ курс",feat:true},{tag:"Тренування",title:"Програма",desc:"Персональна програма тренувань для дому або залу з відеотехнікою.",eur:69,disc:.2,spots:5,total:10,per:"/ програма"}],
  credEye:"🎓 Освіта та сертифікація",credTitle:'Знання, яким можна <b>довіряти</b>',
  credIntro:"Постійно вчуся, щоб давати не поради з інтернету, а перевірені знання.",
  creds:[{y:"2025",t:"Сертифікований фітнес-тренер",d:"Fitness Trainer — ExpertX"},{y:"2026",t:"Mini MBA",d:"Practical Nutrition & Health Coaching, Open European Academy of Economics & Politics (Прага)"},{y:"150 год",t:"Дієтологія та нутриціологія",d:"Basic Dietetics and Nutrition — раціональне харчування та корекція маси тіла"},{y:"",t:"Спеціалізації",d:"Спортивне харчування, психологія харчової поведінки, харчування жінок та дітей"}],
  topics:["Спортивне харчування","Психологія харчової поведінки","Харчування жінок","Інтервальне голодування","Кето та без глютену","Робота зі щитоподібною залозою"],
  ctaTitle:'Готова почати <b>трансформацію</b>?',ctaText:"Напиши мені в Instagram — підберемо програму саме під твої цілі.",ctaBtn:"Написати в Instagram",
  faqEye:"Питання",faqTitle:'Часті <b>запитання</b>',copy:"© 2026 Olena Kostetska · Wrocław",
  faq:[{q:"Чи підійде новачкам?",a:"Так. Я не працюю за шаблонами — програми адаптуються під будь-який рівень і твій ритм життя."},{q:"Як проходить оплата?",a:"Оплата онлайн, деталі узгоджуємо в особистих повідомленнях в Instagram."},{q:"Чи можна без спортзалу?",a:"Так, є програми для дому. Підберемо формат під твої умови та обладнання."}]
 },
 pl:{
  eyebrow:"Trenerka · Modelka fitness · Wrocław 🇵🇱",
  h1:'Twoje <i>wymarzone ciało</i> —<br>zbudujemy je <b>razem</b>',
  herosub:"Jestem Olena — trenerka z Wrocławia. 20 lat w sporcie, startuję na scenie międzynarodowej. Pomogę Ci wrócić do formy bez skrajności.",
  cta1:"Wybierz program",cta2:"O mnie",badge:"na scenie od",
  nav:{about:"O mnie",ach:"Osiągnięcia",process:"Jak pracuję",whom:"Dla kogo",values:"Wartości",services:"Usługi",creds:"Edukacja",faq:"Pytania",navcta:"Wybierz program"},
  offerLabel:"Rabat <b>−20%</b> na wszystkie programy do końca tygodnia",
  tD:"dni",tH:"godz",tM:"min",tS:"sek",
  spotsLabel:"Wolne miejsca:",saveBadge:"−20%",
  fabText:"Napisz",incEye:"📦 Co zawiera",incTitle:"Co <b>otrzymasz</b>",includes:[{t:"Dieta",feat:false,items:["Indywidualny plan żywieniowy","Wyliczenie kalorii i makro","Lista produktów i zamienniki","Zalecenia pod Twój grafik","Wsparcie przy starcie planu"]},{t:"Maraton",feat:true,items:["Program treningowy na cały kurs","Plan żywieniowy","Codzienne wsparcie w grupie","Cotygodniowa kontrola postępów","Motywacja i dyscyplina","Odpowiedzi na pytania od trenerki"]},{t:"Program",feat:false,items:["Osobisty program treningowy","Technika ćwiczeń na wideo","Warianty do domu i na siłownię","Schemat progresji obciążeń","Porady dotyczące regeneracji"]}],
  mq:["20+ lat doświadczenia","Absolutna mistrzyni Polski","Scena międzynarodowa","Dietetyk · nutrycjonista","Mini MBA","Indywidualne podejście"],
  aboutEye:"O mnie",aboutTitle:'Fitness to <b>moja droga</b>',
  aboutP1:"Fitness jest ze mną ponad 20 lat. Przeszłam drogę od dziewczyny trenującej dla siebie do zawodniczki na scenie międzynarodowej.",
  aboutP2:"Wynik to nie magia, tylko system i regularność. Tego uczę moje klientki.",
  aboutQuote:"«W pracy z klientkami łączę 20-letnie doświadczenie treningowe, wiedzę z kursów i osobiste przygotowania do zawodów.»",
  stat1:"lat w sporcie",stat2:"pierwszy start",stat3:"tytuły mistrzowskie Masters",
  achEye:"🏆 Osiągnięcia sportowe",achTitle:'Zdobyte <b>na scenie</b>',
  achIntro:"Zaczęłam w 2014 — brąz już na debiucie. Po przerwie wróciłam silniejsza i startuję w kategorii Fit Model w Polsce i we Włoszech.",
  
  titles:[{i:"🏆",t:"Absolutna mistrzyni Polski — Open Fit Model"},{i:"🥇",t:"Dwukrotna mistrzyni Masters"},{i:"🥈",t:"Srebro EuroMasters (Włochy), Masters 35+ i 40+"},{i:"🏅",t:"TOP-5 Flex Weekend Pro Qualifier, Mediolan"}],
  timeline:[{y:"2014",ev:[{p:"Mistrzostwa Ukrainy (WBPF)",r:"🥉 Brąz — debiut"}]},{y:"2025",ev:[{p:"NPC Poland",r:"🏆 Overall Open Fit Model · 2×🥇 Masters · 🥈 Open Class B"},{p:"EuroMasters (Włochy)",r:"🥈 Masters 35+ · 🥈 Masters 40+"}]},{y:"2026",ev:[{p:"League of Champions Pro Qualifier",r:"2×🥇 Masters · 🥈 Open Class B"},{p:"Natural & Regional Qualifier",r:"Miejsca medalowe w Masters i Novice"},{p:"Flex Weekend Pro Qualifier (Mediolan)",r:"🏅 TOP-5 Fit Model Open Class B"}]}],
  procEye:"🧭 Jak wygląda współpraca",procTitle:'Krok po <b>kroku</b>',
  steps:[{h:"Poznanie",p:"Poznaję Twój rytm, nawyki, zdrowie i cel."},{h:"Ankieta",p:"Wypełniasz ankietę — widzę Twój poziom i ograniczenia."},{h:"Cel",p:"Ustalamy, czego chcesz: schudnąć, wymodelować ciało czy formę na event."},{h:"Plan",p:"Układam dietę i trening pod Twój tryb życia."},{h:"Kontrola",p:"Co tydzień: zdjęcia, pomiary, waga, samopoczucie."},{h:"Korekty",p:"Koryguję plan, by wynik szedł bez stresu dla ciała."}],
  resTitle:"Efekty w 2–3 miesiące",
  results:["zmniejszenie obwodów","spadek wagi","wymodelowane ciało","lepsza forma pośladków i nóg","lepsza postawa","więcej energii","kontrola odżywiania","mniej obrzęków","dyscyplina i rytm","pewność siebie"],
  whoEye:"🎯 Dla kogo",whoTitle:'Z kim <b>pracuję</b>',
  goals:["schudnąć","wymodelować ciało","poprawić formę pośladków, nóg, pleców i ramion","nauczyć się prawidłowo odżywiać","odzyskać pewność siebie","przygotować się do sesji, wakacji lub zawodów"],
  valEye:"💜 Moje wartości",valTitle:'Podejście, w które <b>wierzę</b>',
  values:[{t:"Dyscyplina",p:"To regularne działania tworzą wynik."},{t:"Zdrowie",p:"Forma nie może powstawać kosztem wyczerpania."},{t:"Stabilność",p:"Krótkie zrywy nie dają trwałego efektu."},{t:"Miłość do siebie",p:"Zmiany zaczynają się od troski o siebie, nie od nienawiści do ciała."},{t:"Trwały efekt",p:"Moim celem jest nauczyć Cię utrzymać formę, nie tylko ją osiągnąć."}],
  servEye:"✨ Usługi",servTitle:'Wybierz swój <b>format</b>',
  services:[{tag:"Dieta",title:"Dieta",desc:"Indywidualny plan żywieniowy dopasowany do Twoich celów i trybu życia.",eur:49,disc:.2,spots:6,total:10,per:"/ plan"},{tag:"Najpopularniejsze",title:"Maraton",desc:"Grupowy kurs transformacji: treningi, dieta i codzienne wsparcie.",eur:99,disc:.2,spots:3,total:12,per:"/ kurs",feat:true},{tag:"Trening",title:"Program",desc:"Osobisty plan treningowy do domu lub na siłownię z techniką wideo.",eur:69,disc:.2,spots:5,total:10,per:"/ program"}],
  credEye:"🎓 Edukacja i certyfikaty",credTitle:'Wiedza, której możesz <b>zaufać</b>',
  credIntro:"Ciągle się uczę, żeby dawać sprawdzoną wiedzę, a nie porady z internetu.",
  creds:[{y:"2025",t:"Certyfikowana trenerka fitness",d:"Fitness Trainer — ExpertX"},{y:"2026",t:"Mini MBA",d:"Practical Nutrition & Health Coaching, Open European Academy of Economics & Politics (Praga)"},{y:"150 h",t:"Dietetyka i nutrycjologia",d:"Basic Dietetics and Nutrition — racjonalne odżywianie i korekta masy ciała"},{y:"",t:"Specjalizacje",d:"Żywienie sportowe, psychologia odżywiania, żywienie kobiet i dzieci"}],
  topics:["Żywienie sportowe","Psychologia odżywiania","Żywienie kobiet","Post przerywany","Keto i bez glutenu","Praca z tarczycą"],
  ctaTitle:'Gotowa na <b>transformację</b>?',ctaText:"Napisz do mnie na Instagramie — dobierzemy program pod Twoje cele.",ctaBtn:"Napisz na Instagramie",
  faqEye:"Pytania",faqTitle:'Najczęstsze <b>pytania</b>',copy:"© 2026 Olena Kostetska · Wrocław",
  faq:[{q:"Czy nadaje się dla początkujących?",a:"Tak. Nie pracuję według szablonów — programy dostosowuję do każdego poziomu i Twojego trybu życia."},{q:"Jak wygląda płatność?",a:"Płatność online, szczegóły ustalamy w wiadomości prywatnej na Instagramie."},{q:"Czy mogę ćwiczyć bez siłowni?",a:"Tak, są programy do domu. Dobierzemy format do Twoich warunków i sprzętu."}]
 },
 en:{
  eyebrow:"Coach · Fitness model · Wrocław 🇵🇱",
  h1:'Your <i>dream body</i> —<br>let\'s build it <b>together</b>',
  herosub:"I'm Olena — a coach from Wrocław. 20 years in the sport, competing internationally. I'll help you get in shape without extremes.",
  cta1:"Choose a program",cta2:"About me",badge:"on stage since",
  nav:{about:"About",ach:"Results",process:"How I work",whom:"For whom",values:"Values",services:"Services",creds:"Education",faq:"FAQ",navcta:"Choose a program"},
  offerLabel:"<b>−20%</b> off all programs until the end of the week",
  tD:"days",tH:"hrs",tM:"min",tS:"sec",
  spotsLabel:"Spots left:",saveBadge:"−20%",
  fabText:"Message",incEye:"📦 What's included",incTitle:"What you <b>get</b>",includes:[{t:"Diet",feat:false,items:["Individual nutrition plan","Calorie and macro calculation","Food list and swaps","Recommendations for your schedule","Support at plan launch"]},{t:"Marathon",feat:true,items:["Training program for the whole course","Nutrition plan","Daily support in the group","Weekly progress check","Motivation and discipline","Answers to your questions from the coach"]},{t:"Program",feat:false,items:["Personal training program","Exercise technique videos","Home and gym variants","Load progression scheme","Recovery guidance"]}],
  mq:["20+ years experience","Overall Champion of Poland","International stage","Dietitian · nutritionist","Mini MBA","Individual approach"],
  aboutEye:"About",aboutTitle:'Fitness is <b>my path</b>',
  aboutP1:"Fitness has been with me for over 20 years. I went from a girl training for herself to an athlete on the international stage.",
  aboutP2:"Results aren't magic — they come from a system and consistency. That's what I teach my clients.",
  aboutQuote:"\"With my clients I combine 20 years of training experience, course knowledge and personal competition prep.\"",
  stat1:"years in sport",stat2:"first stage",stat3:"Masters champion titles",
  achEye:"🏆 Competition results",achTitle:'Earned <b>on stage</b>',
  achIntro:"I started in 2014 — bronze on my debut. After a break I came back stronger and compete in Fit Model across Poland and Italy.",
  
  titles:[{i:"🏆",t:"Overall Champion of Poland — Open Fit Model"},{i:"🥇",t:"Two-time Masters Champion"},{i:"🥈",t:"Silver at EuroMasters (Italy), Masters 35+ & 40+"},{i:"🏅",t:"TOP-5 Flex Weekend Pro Qualifier, Milan"}],
  timeline:[{y:"2014",ev:[{p:"Ukraine Championship (WBPF)",r:"🥉 Bronze — debut start"}]},{y:"2025",ev:[{p:"NPC Poland",r:"🏆 Overall Open Fit Model · 2×🥇 Masters · 🥈 Open Class B"},{p:"EuroMasters (Italy)",r:"🥈 Masters 35+ · 🥈 Masters 40+"}]},{y:"2026",ev:[{p:"League of Champions Pro Qualifier",r:"2×🥇 Masters · 🥈 Open Class B"},{p:"Natural & Regional Qualifier",r:"Podium places in Masters and Novice"},{p:"Flex Weekend Pro Qualifier (Milan)",r:"🏅 TOP-5 Fit Model Open Class B"}]}],
  procEye:"🧭 How working together works",procTitle:'Step by <b>step</b>',
  steps:[{h:"We meet",p:"I learn your routine, habits, health and goal."},{h:"Questionnaire",p:"You fill it in — I see your level and limits."},{h:"Goal",p:"We define it: lose weight, tone up, or shape for an event."},{h:"Plan",p:"I build your nutrition and training around your life."},{h:"Check-ins",p:"Weekly: photos, measurements, weight, wellbeing."},{h:"Adjustments",p:"I tweak the plan so results move without stress."}],
  resTitle:"Results in 2–3 months",
  results:["reduced volume","weight loss","a more toned body","better glutes and legs","better posture","more energy","food control","less bloating","discipline and routine","more confidence"],
  whoEye:"🎯 Who it's for",whoTitle:'Who I <b>work with</b>',
  goals:["lose weight","tone the body","improve glutes, legs, back and shoulders","learn to eat properly","regain confidence","prep for a photoshoot, holiday or competition"],
  valEye:"💜 My values",valTitle:'The approach I <b>believe in</b>',
  values:[{t:"Discipline",p:"Regular actions are what create results."},{t:"Health",p:"Shape should never be built at the cost of exhaustion."},{t:"Stability",p:"Short bursts don't give a lasting result."},{t:"Self-love",p:"Change starts with caring for yourself, not hating your body."},{t:"Lasting result",p:"My goal is to teach you to keep your shape, not just reach it."}],
  servEye:"✨ Services",servTitle:'Choose your <b>format</b>',
  services:[{tag:"Nutrition",title:"Diet",desc:"A personal nutrition plan built around your goals, body type and lifestyle.",eur:49,disc:.2,spots:6,total:10,per:"/ plan"},{tag:"Most popular",title:"Marathon",desc:"Group transformation course: training, nutrition and daily support.",eur:99,disc:.2,spots:3,total:12,per:"/ course",feat:true},{tag:"Training",title:"Program",desc:"A personal workout plan for home or gym, with video technique guides.",eur:69,disc:.2,spots:5,total:10,per:"/ program"}],
  credEye:"🎓 Education & certification",credTitle:'Knowledge you can <b>trust</b>',
  credIntro:"I keep learning — so you get proven knowledge, not internet advice.",
  creds:[{y:"2025",t:"Certified Fitness Trainer",d:"Fitness Trainer — ExpertX"},{y:"2026",t:"Mini MBA",d:"Practical Nutrition & Health Coaching, Open European Academy of Economics & Politics (Prague)"},{y:"150 h",t:"Dietetics & Nutrition",d:"Basic Dietetics and Nutrition — rational eating and weight adjustment"},{y:"",t:"Specializations",d:"Sports nutrition, eating psychology, nutrition for women and children"}],
  topics:["Sports nutrition","Eating psychology","Women's nutrition","Intermittent fasting","Keto & gluten-free","Thyroid support"],
  ctaTitle:'Ready to <b>transform</b>?',ctaText:"Message me on Instagram — we'll find the right program for your goals.",ctaBtn:"Message on Instagram",
  faqEye:"Questions",faqTitle:'Frequently <b>asked</b>',copy:"© 2026 Olena Kostetska · Wrocław",
  faq:[{q:"Is it good for beginners?",a:"Yes. I don't work from templates — programs adapt to any level and to your lifestyle."},{q:"How does payment work?",a:"Payment is online; we arrange the details in a direct message on Instagram."},{q:"Can I train without a gym?",a:"Yes, there are home programs. We'll pick a format that fits your setup and equipment."}]
 }
};

export { RATES, priceFor, DATA };
